import praxis_ado.praxis
import praxis_advanced.praxis
import praxis_aws.praxis
import praxis_bash.praxis
import praxis_docker.praxis
import praxis_git.praxis
import praxis_github.praxis
import praxis_matplotlib.praxis
import praxis_os.praxis
import praxis_pandas.praxis
import praxis_python.praxis
import praxis_test.praxis
import praxis_vscode.praxis
